models:
  coco_yolo11n:
    filename: yolo11n.pt
    release: ultralytics-assets-v8.3.0
    url: https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt
    sha256: 0ebbc80d4a7680d14987a577cd21342b65ecfd94632bd9a8da63ae6417644ee1
  aerial_yolo11n_obb:
    filename: yolo11n-obb.pt
    release: ultralytics-assets-v8.4.0
    url: https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11n-obb.pt
    sha256: b62898ebf38940ca4df323863e45ee9d84a1a46d5d11ebdde529fb33aa9f3a32
  aerial_yolo11s_obb:
    filename: yolo11s-obb.pt
    release: ultralytics-assets-v8.4.0
    url: https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11s-obb.pt
    sha256: 43fa63102922e0701501241b307420d24fc55e080816888b18bf8c6f96b1a45a
  aerial_yolo11m_obb:
    filename: yolo11m-obb.pt
    release: ultralytics-assets-v8.4.0
    url: https://github.com/ultralytics/assets/releases/download/v8.4.0/yolo11m-obb.pt
    sha256: 41832a4349c08190335bbc11a8e64726750702eb49cf09abb262bc394a13498c

road_models:
  mask2former_satellite:
    repository: mfaytin/mask2former-satellite
    revision: 558c4959866ddd8dca42c13d24e49ca3e12bb71e
